# Generated by Django 3.2.18 on 2023-03-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.BigIntegerField()),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='career_guidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='test_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tips', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=100)),
                ('requirments', models.CharField(max_length=300)),
                ('no_of_vacancy', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.company')),
            ],
        ),

        migrations.AddField(
            model_name='test_questions',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.vacancy'),
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BigIntegerField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.candidate')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.company')),
            ],
        ),
        migrations.CreateModel(
            name='mock_test_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('cg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.career_guidance')),
            ],
        ),
        migrations.CreateModel(
            name='mock_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.candidate')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.mock_test_questions')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='company_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.login'),
        ),
        migrations.AddField(
            model_name='career_guidance',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.login'),
        ),
        migrations.CreateModel(
            name='candidate_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.login'),
        ),
        migrations.CreateModel(
            name='applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.candidate')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.company')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selector.vacancy')),
            ],
        ),
    ]
