# Generated by Django 3.2.18 on 2023-03-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0002_remove_applied_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(default=11, upload_to=''),
            preserve_default=False,
        ),
    ]
