# Generated by Django 3.2.18 on 2023-04-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0004_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='predicted_score',
            field=models.FloatField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
