# Generated by Django 3.2.18 on 2023-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0006_auto_20230430_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='requirments',
            field=models.TextField(),
        ),
    ]
