# Generated by Django 3.2.18 on 2023-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0007_alter_vacancy_requirments'),
    ]

    operations = [
        migrations.CreateModel(
            name='sortrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateid', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('resumescor', models.IntegerField()),
            ],
        ),
    ]
